[tool.poetry]
name = "repl_python3_Lab2"
version = "0.1.0"
description = ""
authors = ["demonorium <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
prettytable = "^2.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
